export const refs = {
  searchInput: document.querySelector('#search-note'),
  modalBackDrop: document.querySelector('.js-modal-backdrop'),
  addTaskButton: document.querySelector('.js-add-task'),
  cancelModalBtn: document.querySelector('.js-btn-cancel'),
  modalWindow: document.querySelector('.js-modal-window'),
  modalForm: document.querySelector('.js-modal-form'),
  modalInput: document.querySelector('.modal-input'),
  taskList: document.querySelector('.js-task-list'),
  emptyBlock: document.querySelector('.js-empty-block'),
  clearListButton: document.querySelector('.js-clear-list-button'),
  statusSelect: document.getElementById('status'),
  themeButton: document.querySelector('.theme-button'),
  acceptModalBackdrop: document.querySelector('.js-accept-modal-backdrop'),
  acceptModal: document.querySelector('.js-accept-modal-window'),
  acceptCancelButton: document.querySelector('.js-accept-btn-cancel'),
  acceptClearListButton: document.querySelector('.js-accept-btn-clear'),
};
